### PR TITLE
feat(docs): Added first draft of algolia search

### PR DESCRIPTION
**Pull request by Shanugoyanka**
Screenshot 2023-11-29 at 6 45 11 PM
Screenshot 2023-11-29 at 6 45 30 PM
Screenshot 2023-11-29 at 6 45 44 PM

### CODE REVIEW

**Comment by Shanugoyanka** [comment]
**Things need to be done**
1. Add a step in CI to continuously index data, as soon as there is change in mdx files
2. Secret key to index data and fetch it from Algolia is still in code, will read it via ENVs once we shift to company's algolia account
3. The logging/saving of searches is paused in this for a while, algolia handles it on it own

Open for suggestion while indexing data and rendering it

@devjsc @ejfitzgerald

**Comment by Shanugoyanka** [comment]
Screenshot 2023-11-30 at 12 49 47 AM
Added tags in search results rendering

**Comment by devjsc** [comment]
hey @Shanugoyanka how do you trigger an index of the site?

**Comment by Shanugoyanka** [comment]
> hey @Shanugoyanka how do you trigger an index of the site?

So in CI I have commented the step of running node index-data-to-alogolia.js for now, as running this every-time we make a build will create a lots of repeated data in Algolia, so for that I will figure out a way in which, we will check if the commit contains any mdx file changes, then only index the changes of that committed file only, as rest of the changes already exists

@devjsc

**Pull request merged**
