### PR TITLE
fix(docs): fix bug in tooltip hover

### PR DESCRIPTION
**Pull request by joshua-demo**
## Proposed Changes

_[Able to hover over tool tip message and click on Agentverse link]_

## Types of changes

_What type of change does this pull request make (put an `x` in the boxes that apply)?_

- [ ] Content update.
- [x] Bug fix (non-breaking change that fixes an issue).
- [ ] New feature added (non-breaking change that adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to stop working as expected).
- [ ] Something else (e.g., tests, scripts, example, deployment, infrastructure).

## Checklist

_Put an `x` in the boxes that apply:_

- [x] I have read the [CONTRIBUTING](https://github.com/fetchai/docs/blob/main/CONTRIBUTING.md) guide
- [x] Checks and tests pass locally

[Screencast from 2024-11-25 14-43-23.webm](https://github.com/user-attachments/assets/1fef76d5-d2a1-416e-8c5d-12488589b03f)

### CODE REVIEW

**Comment by devjsc** [comment]
hey @joshua-demo nice catch, you're right the hover effect isn't very good. I think for best UX we should have it click on, click anywhere off. Would you like to update for this functionality, else we'll fix this 👍

**Comment by joshua-demo** [comment]
hi @devjsc I found it more common when there is an information svg, for it to be a tooltip where it will automatically hide the modal after a small amount of time when hovering off the tootip modal or the information svg. If you still think the button version is better, I can also update for that functionality.

**Comment by devjsc** [comment]
Interesting, i thought best UX for modals is click anywhere for off, expected behaviour (imo): 

- click on tooltip icon, popup displays
- scroll, click on tooltip icon, or click anywhere else on screen popup closes.

What do you think @gautamgambhir97 ?

**Comment by devjsc** [comment]
@gautamgambhir97 can you update this PR 

- click on tooltip icon, popup displays
 - scroll, click on tooltip icon, or click anywhere else on screen popup closes.

**Comment by gautamgambhir97** [comment]
> @gautamgambhir97 can you update this PR
> 
> * click on tooltip icon, popup displays
> * scroll, click on tooltip icon, or click anywhere else on screen popup closes.

Yeah,  I'll update it

**Pull request merged**
